Add references to `Registry.IsRegistered()`
hamba/avro pull request #220
Opened 2022-11-30 22:33 UTC by deluan

This PR adds the `references` parameter to the Registry.IsRegistered(), as per the official [Schema Registry API documentation](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)):

> POST /subjects/(string: subject)
> 
> Request JSON Object:
>  	
> - schema – The schema string
> - schemaType – Defines the schema format: AVRO (default), PROTOBUF, JSONSCHEMA (Optional)
> - references – Specifies the names of referenced schemas (Optional). To learn more, see [Schema References](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas).
> 

Note that this will be a breaking change to the `Registry` interface, as the `IsRegistered()` method signature changes.

2022-12-01 18:27 UTC, nrwiersma requested changes
This is a breaking change and cannot be merged as is. It is also missing tests.

2022-12-01 21:57 UTC, deluan commented
As suggested, I created a new function, `IsRegisteredWithRefs`. Also added tests, but not sure if they can be written, I don't usually use testfy assertions, prefer gomega. Let me know if anything is missing or can be improved.

2022-12-02 14:21 UTC, deluan commented
I abbreviated the `references` parameter name, to keep the method signature in one line.  The alternative would be to break the line which IMHO would make the code less readable. Let me know if this is ok.

2022-12-02 15:35 UTC, nrwiersma approved these changes
LGTM 🎉

2022-12-02 15:36 UTC, merged