deserialize functionality
hamba/avro pull request #236
Opened 2023-02-08 21:41 UTC by nucccc

Proposing deserialize functionality to client, i.e. the capability to extrapolate the id of the schema from the payload, as described in the [confluent docs regarding the wire format](https://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#wire-format).

Basically a kafka message has five "header bytes" in the payload, with the first byte being the magic byte, always zero, and the remaining four representing the id of the schema.

Added a private function

`func extractSchemaIDFromPayload(payload []byte) (int, error)`

which allows to obtain the schema_id as integer, then used by method

`func (c *Client) DeserializePayload(
	ctx context.Context,
	payload []byte,
	target interface{},
) error`

which gets the schema and uses it to deserialize the obtained payload in input.

Thank you for the attention and the work, in case of interest I will be available for the review and the eventual corrections.

Nuc

2023-02-12 08:12 UTC, nrwiersma commented
Hi,

To start, thanks for the contribution. I have had a good think about this and I am now convinced this does not belong in the `registry.Client`. I would suggest to become its own concept, perhaps `registry.Decoder` that takes a `registry.Client` and optionally an `avro.API`. This allows customisation of how the avro is decoded, but in the simplest case can use the `avro.DefaultConfig`. I think it would also allow for static byte payloads as well as a stream reader mechanics.

What do you think?

2023-02-13 22:22 UTC, nucccc commented
Thank you for the consideration and the suggestion.
I agree with with what you are saying, while I just implemented a functionality, a separate concept is by far a more reasonable design choice. I suggest the name `Deserializer`, since to what I see that is the name most often used in the Apache Kafka ecosystem, as for example in [this link](https://kafka.apache.org/21/javadoc/org/apache/kafka/common/serialization/Deserializer.html) or [this other link](https://quarkus.io/blog/kafka-serde/).

Given time, I would gladly do my best to implement the concept. Do you think a new file could do the job? Maybe still in the same package `registry`, something like `deserializer.go`.

I'm open to any suggestion or objection! Thank you for the work!

2023-02-14 04:43 UTC, nrwiersma commented
I would stay away from the name `Deserializer` as Kafka is Java and therefore uses Java naming. In Go `Decoder` is far far more common: see [json.Decoder](https://pkg.go.dev/encoding/json#Decoder) and [go-json.Decoder](https://github.com/goccy/go-json/blob/master/decode.go#L15) and [avro.Decoder](https://github.com/hamba/avro/blob/main/decoder.go#L9).

It is its own concept so a new file `decoder.go` in the `registry` package would be good.

2023-02-20 09:38 UTC, nucccc commented
Hi,
thank you for the attentions.

I created `decoder.go`, `decoder_test.go` and `decoder_internal_test.go` where I moved everything pertaining to the new `Decoder` struct/concept.

To be initialized it requires a `*registry.Client`, and implements DefaultConfig as the API.
Next, I will try to create a method returning such as 'WithAPI' to return a new decoder with a different API. However I value a lot your opinion on such choice. Up to my limited experience, I would not create two different constructors.

Hoping it to be useful!

Nuc

2023-02-20 10:15 UTC, nucccc commented
I included the possibility to set the API in the same way as you do for the client, with DecoderFunc options.

I hope the contribution to be useful, for any modification required I'm available, thank you for the consideration.

I saw that there needs to be a merging with the main branch, I don't exactly know who/how is that work supposed to be done, but I'm available for any necessity.

Nuc

2023-02-20 15:54 UTC, nrwiersma requested changes
Thanks for the contribution, I have left a couple nitpick comments.

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder_test.go
> +func TestError_DeserializePayload(t *testing.T) {
```suggestion
func TestDecoder_DeserializePayloadHandlesError(t *testing.T) {
```

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder_test.go
> +		_, _ = w.Write([]byte(`{"schema":"boh"}`))
```suggestion
		_, _ = w.Write([]byte(`{"schema":"boh"}`))
```

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder_internal_test.go
> +func TestDeserialize_extractSchemaIDFromPayload(t *testing.T) {
```suggestion
func TestExtractSchemaIDFromPayload(t *testing.T) {
```

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder_internal_test.go
> +func TestDeserializeError_extractSchemaIDFromPayload(t *testing.T) {
```suggestion
func TestExtractSchemaIDFromPayload_HandlesError(t *testing.T) {
```

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder.go
> +func (d *Decoder) DeserializePayload(
```suggestion
func (d *Decoder) Decode(
```
It would be more natural for a `Decoder` to `Decode`.

2023-02-20 15:54 UTC, nrwiersma commented on registry/decoder.go
> +type Decoder struct {
The ordering here is a little weird. Conventionally, it is best where possible to keep the struct and its constructor together. So I would order like so (in short form):
```
type DecoderFunc

func WithAPI

type Decoder

func NewDecoder

// all the other code ...

func extractSchemaIDFromPayload
```

The unattached function can either be at the end or just above `Decode`, dealers choice.

2023-02-20 17:35 UTC, nucccc commented
> Thanks for the contribution, I have left a couple nitpick comments.

I made my best to update everything as requested, and I think to have modified everything accordingly

2023-02-20 17:38 UTC, nrwiersma approved these changes
LGTM 🎉 Thanks again for the contribution

2023-02-20 17:40 UTC, nucccc commented
Thank you for the attention and the guidance!

2023-02-20 17:41 UTC, merged