feat: accept convertible types - resolves #67
hamba/avro pull request #250
Opened 2023-04-04 00:33 UTC by TuSKan

2023-04-05 04:44 UTC, nrwiersma requested changes

2023-04-05 04:44 UTC, nrwiersma commented on codec_fixed.go
> +		case typ.Type1().ConvertibleTo(durType) && ls.Type() == Duration:
It would be more efficient to do the `typ.Type1()` once and reuse it. It is fairly expensive. This goes for all switch checks.

2023-04-08 10:35 UTC, nrwiersma approved these changes
LGTM 🎉

2023-04-08 10:35 UTC, merged

2023-04-08 10:35 UTC, nrwiersma commented
Thanks for the contribution.

2023-04-10 13:01 UTC, TuSKan commented
Thank you very much for accepting suggestions for improvements to your package. This will allow me to solve an important limitation in my application.
Many thanks also for quick response and iteration through the process.
There are some small improvements in the text of the README to better explain the new feature.
Let me know if you want another commit or prefer to do it yourself, or later.
Regards