Add recursive structs supported
hamba/avro pull request #335
Opened 2023-12-21 12:47 UTC by RyougiNevermore

just use processing cache, and no performance loss.

2023-12-21 14:12 UTC, nrwiersma commented on codec_record.go
> +	cfg.addProcessingDecoderToCache(schema.Fingerprint(), typ.RType(), dec)
This sets up a race in parallel processing that will lead to SIGSEGV.

2023-12-21 16:39 UTC, RyougiNevermore commented
I'm not sure about the results of golangci-lint. any help?

2023-12-23 07:24 UTC, RyougiNevermore commented
uhhh, if support disable cache mode, maybe use some one like ctx, and it will cost more performance, from 1400 ns/op up to 1700 ns/op in.
and there is a bug about big.rat in generic decoder..., so can use *big.rat insteadof big.rat?

2024-01-12 11:07 UTC, nrwiersma requested changes
Please rebase and clean up. Seems a lot of stuff is left over or unused.

2024-01-12 11:07 UTC, nrwiersma commented on processings.go
> +	group *singleflight.Group
This is not needed for the local option.

2024-01-12 11:07 UTC, nrwiersma commented on processings.go
> +	key      []byte
I dont get what this is used for?

2024-01-12 11:07 UTC, nrwiersma commented on internal/mmhash/hash.go
> +package mmhash
This seems to be unused.

2024-06-25 12:23 UTC, nrwiersma commented
Fixed by #413

2024-06-25 12:23 UTC, closed without merging