add support for recursive schemas & structs
hamba/avro pull request #413
Opened 2024-06-23 19:44 UTC by adrianiacobghiula

2024-06-24 04:19 UTC, nrwiersma commented
Any particular reason you chose this approach over passing a DecoderContext/EncoderContext through?

2024-06-24 04:42 UTC, adrianiacobghiula commented
Just a matter of personal way of coding, I tend to have the functions on a struct rather than having free-floating with large names `createDecoderOfMap()` vs `encoderCreator.ofMap()` because of input parameters, long-names & cohesion

2024-06-24 05:18 UTC, nrwiersma commented
Fair. This has however created some inconsistency in the module as a whole. For example `createDefaultDecoder` still exists with the old signature. `(d decoderCreator) newEfaceDecoder` is actually a constructor but has been attached.

2024-06-24 05:58 UTC, adrianiacobghiula commented
Pushed improvements. I do have one question: What does `eface` stands for ?

2024-06-24 06:00 UTC, nrwiersma commented
Interfaces are split into 2 types, an empty interface (interface{} or any) `eface` and a populated (has methods) interface `iface`.

2024-06-24 07:00 UTC, nrwiersma commented
The issue this poses is that it fundamentally changes the codebase far beyond what is required to implement the feature. In fact I see a couple ways to do it without putting everything under a struct. Part of this also subtly changes how this works in ways I don't fully understand the impact of yet. I am not making any argument of the relative benefits of either approach. Both are perfectly valid, and were I to completely rewrite today, perhaps a different approach would be chosen.

As an example, this changes the benchmark of the library for the worse (~224ns to ~230ns), but it would be very difficult to pin down exactly were the degraded performance comes from, small as it may be.

2024-06-24 07:12 UTC, adrianiacobghiula commented
So you would not have decoderCreator or encoderCreator but replace the parameter `cfg *frozenConfig` to another object like `DecoderContext` (that contains the `cfg *frozenConfig` & the map ?) to every function `createDecoderOfMap`, `decoderOfType`, `createDecoderOfMarshaler` ?

2024-06-24 07:14 UTC, nrwiersma commented
Yes. That seems like it should work.

2024-06-24 08:35 UTC, adrianiacobghiula commented
@nrwiersma pushed using `DecoderContext` & `EncoderContext`

2024-06-25 05:18 UTC, nrwiersma requested changes
Nice addition, thanks. A couple comments.

2024-06-25 05:18 UTC, nrwiersma commented on codec.go
> +		key := cacheKey{fingerprint: schema.Fingerprint(), rtype: typ.RType()}
I think this should use `CacheFingerprint` which takes defaults into account.

2024-06-25 05:18 UTC, nrwiersma commented on codec.go
> +		key := cacheKey{fingerprint: schema.(*RefSchema).Schema().Fingerprint(), rtype: typ.RType()}
Same here. I think it needs to use `CacheFingerprint`.

2024-06-25 05:18 UTC, nrwiersma commented on .gitignore
> +.idea
This should be moved to your global `.gitignore`. If we support 1 platform, we must support all, and there are very very many.

2024-06-25 06:18 UTC, nrwiersma requested changes

2024-06-25 06:18 UTC, nrwiersma commented on codec.go
> +		key := cacheKey{fingerprint: schema.CacheFingerprint(), rtype: typ.RType()}
Composite schemas are only a thing for decoding. 
```suggestion
		key := cacheKey{fingerprint: schema.Fingerprint(), rtype: typ.RType()}
```

2024-06-25 06:18 UTC, nrwiersma commented on codec.go
> +		key := cacheKey{fingerprint: schema.(*RefSchema).Schema().CacheFingerprint(), rtype: typ.RType()}
```suggestion
		key := cacheKey{fingerprint: schema.(*RefSchema).Schema().Fingerprint(), rtype: typ.RType()}
```

2024-06-25 06:25 UTC, nrwiersma approved these changes
LGTM 🎉 Thanks for the contribution.

2024-06-25 06:25 UTC, merged